targets:
  $default:
    builders:
      swagger_filter|swagger_filter:
        enabled: true

builders:
  swagger_filter:
    import: "package:swagger_filter/builder.dart"
    builder_factories: ["swaggerFilterBuilder"]
    build_extensions: {".dart": [".swagger_filtered"]}
    auto_apply: root_package
    build_to: source
    defaults:
      options:
        output_dir: "./filtered"
        swaggers:
          - source: "https://raw.githubusercontent.com/epam-cross-platform-lab/swagger-dart-code-generator/master/example/input_folder/pet_service_json.json"
            include_paths: ["/pet"]
            output: "pet_service.json" 