name: swagger_filter
description: A powerful tool to filter and extract specific APIs from Swagger/OpenAPI documents, supporting both OpenAPI 2.0 and 3.0 formats.
version: 1.0.0
homepage: https://github.com/yourname/swagger_filter
repository: https://github.com/yourname/swagger_filter

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  yaml: any
  http: any
  path: any
  build: any
  args: any

dev_dependencies:
  build_runner: any
  lints: ^5.0.0
  test: ^1.24.0
