# yaml-language-server: $schema=./schema/swagger_filter_schema.json

# Swagger Filter Configuration
# This file uses JSON Schema for validation and IDE support

output_dir: "./filtered"

swaggers:
  - source: "https://raw.githubusercontent.com/epam-cross-platform-lab/swagger-dart-code-generator/master/example/input_folder/pet_service_json.json"
    include_paths: ["/pet"]
    output: "pet_service.json" 